// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptZzJ5pzf26E5iEDGoL2Lr1SZpRXmXcM',
    appId: '1:782580474549:web:5398232848943852b7d4fc',
    messagingSenderId: '782580474549',
    projectId: 'primeway-fa5e5',
    authDomain: 'primeway-fa5e5.firebaseapp.com',
    storageBucket: 'primeway-fa5e5.appspot.com',
    measurementId: 'G-TM1G56MF74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNw-9pivOru6a2ll91LpP8uMEAn6u2Rw',
    appId: '1:782580474549:android:b4b2399811b0ed22b7d4fc',
    messagingSenderId: '782580474549',
    projectId: 'primeway-fa5e5',
    storageBucket: 'primeway-fa5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBlgmvTNTRzP0fHkIc_zhxCmoVroHTLc',
    appId: '1:782580474549:ios:ed35c2e0761e3760b7d4fc',
    messagingSenderId: '782580474549',
    projectId: 'primeway-fa5e5',
    storageBucket: 'primeway-fa5e5.appspot.com',
    androidClientId: '782580474549-1ql28cgbq76uutmi14r8baof2nk8oac3.apps.googleusercontent.com',
    iosClientId: '782580474549-5e0mrmstru1vm78ar8ggkpbhuik2hihs.apps.googleusercontent.com',
    iosBundleId: 'com.example.primewayAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaBlgmvTNTRzP0fHkIc_zhxCmoVroHTLc',
    appId: '1:782580474549:ios:ed35c2e0761e3760b7d4fc',
    messagingSenderId: '782580474549',
    projectId: 'primeway-fa5e5',
    storageBucket: 'primeway-fa5e5.appspot.com',
    androidClientId: '782580474549-1ql28cgbq76uutmi14r8baof2nk8oac3.apps.googleusercontent.com',
    iosClientId: '782580474549-5e0mrmstru1vm78ar8ggkpbhuik2hihs.apps.googleusercontent.com',
    iosBundleId: 'com.example.primewayAdminPanel',
  );
}
